BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[trips] ADD [returnTripId] NVARCHAR(1000);

-- AddForeignKey
ALTER TABLE [dbo].[trips] ADD CONSTRAINT [trips_returnTripId_fkey] FOREIGN KEY ([returnTripId]) REFERENCES [dbo].[trips]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
